#!/bin/sh
### BEGIN INIT INFO
# Provides:          cml-scd
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: control cml-scd start at boot time
# Description:       control CML security helper daemon (cml-scd) start at
#                    boot time needed for cmld
### END INIT INFO

DAEMON=/usr/sbin/cml-scd

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

start_scd_daemon() {
	if [ ! -d /var/log/cml ]; then
		mkdir -p /var/log/cml
	fi
	start-stop-daemon --start --quiet --oknodo -b --exec $DAEMON
}

stop_scd_daemon() {
	start-stop-daemon --stop --quiet --signal TERM --oknodo --exec $DAEMON
}

case "$1" in
  start)
        log_daemon_msg "Starting CML security helper daemon" "cml-scd"
        start_scd_daemon
        log_end_msg $?
        ;;
  stop)
        log_daemon_msg "Stopping CML security helper daemon" "cml-scd"
        stop_scd_daemon
        log_end_msg $?
        ;;
  restart|force-reload)
        log_daemon_msg "Restarting CML security helper daemon" "cml-scd"
        stop_scd_daemon
        sleep 1
        start_scd_daemon
        log_end_msg $?
        ;;
  status)
        status_of_proc "$DAEMON" "cml-scd" && exit 0 || exit $?
        ;;
  *)
        N=/etc/init.d/cml-scd
        echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
        exit 1
        ;;
esac

exit 0

